"""
Django settings for lastmeal project.

Generated by 'django-admin startproject' using Django 3.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '3k9)@d=3f@g2%6=3%2#_1zeu&mvfleg9nm&_o2tm0h+mwb&inm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '.compute.amazonaws.com',
    '*',
    'j3d205.p.ssafy.io',
    'j3d205.p.ssafy.io:80',
    'j3d205.p.ssafy.io:8000',
    'j3d205.p.ssafy.io:3306'
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Package
    'rest_framework',
    'drf_yasg',
    'corsheaders',

    # APP
    'accounts',
    'menus',
    'etc',

    # -- 카카오로그인 --
    # third party
    # django-rest-auth
    'rest_framework.authtoken',
    'rest_auth',

    # django-allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_auth.registration',

    # provider
    # 카카오 로그인 기능하기 위해 필수
    'allauth.socialaccount.providers.kakao',
    # -- 카카오로그인 끝 --

    # ssl
    #'sslserver'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',                    # CORS
    'django.middleware.security.SecurityMiddleware',            # https
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'lastmeal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lastmeal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'HDMD',  # DB이름
        'USER': 'root',  # 사용자 이름
        'PASSWORD': 'hdmd205',  # 비밀번호
        'HOST': 'j3d205.p.ssafy.io',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET sql_mode="STRICT_TRANS_TABLES"',
            #'ssl': {
            #        #'cert': '/etc/letsencrypt/live/j3d205.p.ssafy.io/fullchain.pem',
            #        #'key': '/etc/letsencrypt/live/j3d205.p.ssafy.io/privkey.pem',
            #        'cert': '/home/ubuntu/fullchain.pem',
            #        'key': '/home/ubuntu/privkey.pem',
            #}
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ko-KR'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static')
# ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/') # 서버에 올리면 우분투 절대경로 넣기

# AUTH_USER_MODEL = 'accounts.User'

# -- 카카오 로그인 --

# 사이트 ID 부여
SITE_ID = 1

# 소셜 로그인 provider 설정
# 실서비스 상에서 이런 기밀 정보는 settings.py가 아닌 다른 파일(secrets.json 등)에 분리해야 한다.
SOCIALACCOUNT_PROVIDERS = {
    'kakao': {
        'APP': {
            'client_id': 'e716238bbedcf52fc2c99a941276ce4c',
            'secret': 480495,
            'key': ''
        }
    }
}

# rest framework
# 세션 인증, jwt 인증 사용
# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.IsAuthenticated',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#         'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
#     ],
# }

# 선택설정
ACCOUNT_AUTHENTICATED_LOGIN_REDIRECTS = True
LOGIN_REDIRECT_URL = "/"
ACCOUNT_AUTHENTICATED_LOGOUT_REDIRECTS = True
ACCOUNT_LOGOUT_REDIRECT_URL = "/"


# 참고 : https://code4human.tistory.com/entry/Django-Django-REST-frameworkDRF-%ED%99%98%EA%B2%BD%EC%97%90%EC%84%9C-%EC%86%8C%EC%85%9C%EB%A1%9C%EA%B7%B8%EC%9D%B8kakao-%EA%B5%AC%ED%98%84-%EA%B8%B0%EB%A1%9D
# -- 카카오 로그인 끝 --


# CORS
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

CORS_ALLOW_HEADERS = (
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
)

####################################################################################
#SECURE_SSL_REDIRECT = True
## 쿠키 설정
#SESSION_COOKIE_SECURE = True
#CSRF_COOKIE_SECURE = True
## 프록시 설정
#SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')