# Generated by Django 3.1.1 on 2020-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberno', models.AutoField(db_column='memberNo', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profilepath', models.CharField(blank=True, db_column='profilePath', max_length=255, null=True)),
                ('nickname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
