# Generated by Django 3.1.1 on 2020-10-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('checkno', models.AutoField(db_column='checkNo', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checkList',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('diseaseno', models.AutoField(db_column='diseaseNo', primary_key=True, serialize=False)),
                ('diseasename', models.CharField(db_column='diseaseName', max_length=255)),
                ('diseaseinfo', models.CharField(db_column='diseaseInfo', max_length=255)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberno', models.AutoField(db_column='memberNo', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('profilepath', models.CharField(blank=True, db_column='profilePath', max_length=255, null=True)),
                ('nickname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutritional',
            fields=[
                ('nutritionalno', models.AutoField(db_column='nutritionalNo', primary_key=True, serialize=False)),
                ('nutritionalname', models.CharField(blank=True, db_column='nutritionalName', max_length=255, null=True)),
                ('tan', models.IntegerField(blank=True, null=True)),
                ('dan', models.IntegerField(blank=True, null=True)),
                ('ji', models.IntegerField(blank=True, null=True)),
                ('dang', models.IntegerField(blank=True, null=True)),
                ('na', models.IntegerField(blank=True, null=True)),
                ('cal', models.IntegerField(blank=True, null=True)),
                ('col', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutritional',
                'managed': False,
            },
        ),
    ]
